# Generated by Django 4.0.6 on 2022-09-16 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techbro', '0013_alter_showcase_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcartt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_item', models.IntegerField(default=1)),
                ('c_date', models.DateTimeField(auto_now=True)),
                ('c_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('c_price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('cart_code', models.CharField(default='a', max_length=255)),
                ('paid', models.BooleanField(default=False)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techbro.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopcartt',
                'verbose_name_plural': 'Shopcartts',
                'db_table': 'shopcartt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paymentt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('phone', models.CharField(default='a', max_length=50)),
                ('address', models.CharField(default='a', editable=False, max_length=50)),
                ('city', models.CharField(default='a', editable=False, max_length=50)),
                ('cart_code', models.CharField(max_length=255)),
                ('pay_code', models.CharField(max_length=36)),
                ('paid', models.BooleanField(default=False)),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('admin_note', models.CharField(max_length=255)),
                ('admin_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
