# Generated by Django 4.0.6 on 2022-08-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0003_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cereal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='pudding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='tea',
            field=models.BooleanField(default=True),
        ),
    ]
