# Generated by Django 4.0.6 on 2022-08-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0004_dish_cereal_dish_pudding_dish_tea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cereal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='pudding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='tea',
            field=models.BooleanField(default=False),
        ),
    ]
