# Generated by Django 4.0.6 on 2022-08-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0006_rename_cereal_dish_appetizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(default='a'),
        ),
    ]
