# Generated by Django 4.0.6 on 2022-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0009_alter_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default='pix.png', null=True, upload_to='food'),
        ),
    ]
