# Generated by Django 4.0.6 on 2022-08-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0010_dish_special_alter_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=50)),
                ('show_txt', models.CharField(max_length=250)),
                ('show_img', models.ImageField(default='show.jpg', upload_to='showcase')),
            ],
            options={
                'verbose_name': 'Showcase',
                'verbose_name_plural': 'Showcase',
                'db_table': 'showcase',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='showcase1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='showcase2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='showcase3',
            field=models.BooleanField(default=False),
        ),
    ]
