# Generated by Django 4.0.6 on 2022-08-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0012_remove_dish_showcase1_remove_dish_showcase2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showcase',
            options={'managed': True, 'verbose_name': 'Showcase', 'verbose_name_plural': 'Showcases'},
        ),
    ]
